import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle, Circle, Code2, Layers } from 'lucide-react';

export default function StudyPlanPreviewCard() {
  const [hovered, setHovered] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, x: 50, y: 20 }}
      animate={{ opacity: 1, x: 0, y: [0, -10, 0] }}
      transition={{ 
        opacity: { duration: 0.8, delay: 0.6 },
        x: { duration: 0.8, delay: 0.6, type: "spring", stiffness: 100 },
        y: { duration: 6, repeat: Infinity, ease: "easeInOut" }
      }}
      whileHover={{ scale: 1.05, rotateX: 5, rotateY: -5, z: 50 }}
      onHoverStart={() => setHovered(true)}
      onHoverEnd={() => setHovered(false)}
      style={{ transformStyle: 'preserve-3d' }}
      className="relative w-full max-w-sm rounded-2xl bg-white/5 border border-white/10 p-6 backdrop-blur-xl shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]"
    >
      {/* Decorative top gradient */}
      <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-primary/50 via-primary to-primary/50 rounded-t-2xl opacity-50"></div>

      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center">
            <Code2 className="text-primary w-5 h-5" />
          </div>
          <div>
            <h3 className="text-white font-semibold text-lg leading-tight">Your Plan</h3>
            <p className="text-gray-400 text-xs">Generated by AI</p>
          </div>
        </div>
        <div className="px-3 py-1 rounded-full bg-white/10 text-xs font-medium text-white border border-white/5">
          Week 1
        </div>
      </div>

      {/* Content area */}
      <div className="space-y-4">
        {/* Day 1 */}
        <div className="group relative p-4 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors">
          <div className="flex justify-between items-center mb-2">
            <span className="text-primary font-medium text-sm">Day 1</span>
            <span className="text-xs text-gray-400">Today</span>
          </div>
          <h4 className="text-white font-medium mb-1">Arrays & Hashing</h4>
          <div className="flex items-center gap-2 text-sm text-gray-300">
            <Layers className="w-4 h-4 text-gray-400" />
            <span>5 Problems</span>
          </div>
          <div className="absolute -right-2 -top-2 opacity-0 group-hover:opacity-100 transition-opacity">
            <CheckCircle className="text-green-400 w-5 h-5 bg-black rounded-full" />
          </div>
        </div>

        {/* Day 2 */}
        <div className="p-4 rounded-xl bg-white/5 border border-white/5 opacity-70">
          <div className="flex justify-between items-center mb-2">
            <span className="text-gray-300 font-medium text-sm">Day 2</span>
            <span className="text-xs text-gray-500">Tomorrow</span>
          </div>
          <h4 className="text-gray-300 font-medium mb-1">Sliding Window</h4>
          <div className="flex items-center gap-2 text-sm text-gray-400">
            <Layers className="w-4 h-4 text-gray-500" />
            <span>4 Problems</span>
          </div>
        </div>
      </div>

      {/* Glow effect that follows hover */}
      <AnimatePresence>
        {hovered && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 rounded-2xl pointer-events-none shadow-[0_0_40px_rgba(225,29,72,0.15)] ring-1 ring-primary/20"
            style={{ zIndex: -1 }}
          />
        )}
      </AnimatePresence>
    </motion.div>
  );
}
